# 上下文初始化加载
info:
  name: lession-1-website
#端口
server:
  port: 8081

# 其他配置项参考
# org.springframework.cloud.netflix.eureka.EurekaClientConfigBean
# org.springframework.cloud.netflix.eureka.EurekaInstanceConfigBean

# 配置eureka
eureka:
  client:
    # 作为接口提供者，注册到eureka上面
    registerWithEureka: true
    # 从eureka上面拉取其他系统的信息
    # 知道短信系统部署了哪些机器
    fetchRegistry: true
    # eureka server地址
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # 间隔多久刷新一次本地缓存
    registryFetchIntervalSeconds: 3
    # 心跳包发送间隔：默认30秒
    leaseRenewalIntervalInSeconds: 3
    # 心跳超时时间： 超过这个时间还没有心跳，则会被server端剔除掉，默认90秒
    leaseExpirationDurationInSeconds: 9